== https://medium.com/@marcifey/insertion-sort-in-ruby-b538c55591f4/[Insertion Sort]
[subs="quotes,attributes"]
.http://gist.asciidoctor.org/?github-rpokrzywniak%2FSmellingCode%2F%2FWTFCode.adoc[Colored]
....
def insertion_sort(array)
  [red]#raise# ArgumentError, 'no strings allowed' [green]#if# array.[blue]#is_a?# String  [red]#1.1# + [green]#1.3# + [blue]#1#
  [red]#raise# ArgumentError, 'no ints allowed' [green]#if# array.[blue]#is_a?# Integer    [red]#1.1# + [green]#1.3# + [blue]#1#
  [red]#raise# ArgumentError, 'no floats allowed' [green]#if# array.[blue]#is_a?# Float    [red]#1.1# + [green]#1.3# + [blue]#1#
  [red]#if# array.[green]#length# [blue]#==# 0    [red]#1.3# + [green]#22/15# + [blue]#1.2#
    return array
  end
  final [red]#=# [green]#[array[0]]#          [red]#2.2# + [green]#2.5#
  array.[red]#delete_at#(0)                   [red]#1.0#
  # main code
  for i in array
    final_index [red]#=# [green]#0#                         [red]#2.2# + [green]#1.3#
    while final_index [red]#<# final.[green]#length#   	[red]#1.2# + [green]#22/15#
      [red]#if# i [green]#<=# final[final_index]          [red]#1.3# + [green]#1.3#
        final.[red]#insert#(final_index,i)              [red]#1.55#
        break
      [red]#elsif# final_index [green]#==# final.[blue]#length#[yellow]#*-*# 1   [red]#22/15# + [green]#1.2# + [blue]#22/15# + [yellow]#1.6#
        final.[red]#insert#(final_index[blue]#*+1*#,i)        [red]#1.55# + [blue]#1.55#
        break
      end
      final_index[red]#*+=*#1                                [red]#1.55#
    end
  end
  # output
  final
end
....

  flog -ad insertion-sort.rb
    29.6: flog total
    29.6: flog/method average

    29.6: main#insertion_sort              insertion_sort.rb:1-25
     7.8:   branch                         #1.3
     4.4:   length                         #22/15
     4.4:   assignment                     #2.2
     3.3:   raise                          #1.1
     3.1:   insert                         #1.55
     3.1:   +                              #1.55
     3.0:   is_a?                          #1
     2.5:   []                             #2.5
     2.4:   ==                             #1.2
     1.6:   -                              #1.6
     1.3:   lit_fixnum                     #1.3
     1.3:   <=                             #1.3
     1.2:   <                              #1.2
     1.0:   delete_at                      #1.0
